spring:
  database: 
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SENADO_SED
    cachePrepStmts: true
    prepStmtCacheSize: 1000
    prepStmtCacheSqlLimit: 2048
    maximumPoolSize: 100
    minimumIdle: 5
    leakDetectionThreshold: 15000
    connectionTimeout: 1000
    usuario: postgres
    contrasena: DDANH42Cr2O7
    #adminadmin